### ISSUE TITLE
Display raw html text

### ISSUE THREAD

**Issue by volkodavs** [tarmstrong/redmine_google_docs#5]
Hello! 
I faced with problem, my steps:

1) Add document - {{googledoc(1um-eRF9Iny_SftruFUn1l1OBwQuJZBpAXlfEzTvLFcg)}}
2) See raw html <iframe src='https://docs.google.com/document/d/1um-eRF9Iny_SftruFUn1l1OBwQuJZBpAXlfEzTvLFcg' width='100%' height='800'></iframe> 

Install google doc plugin version: 0.0.2

Environment:
  Redmine version                       2.2.3.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                              3.2.12
  Environment                              production
  Database adapter                         Mysql2

Any idea, how to solve problem? 
It could be caused by some other plugins which i installed?

**Comment by volkodavs** [comment]
.html_safe solve problem, it's for local use so i could use it, but if it's will be in internet im not recomend, because of XSS attacks

**Comment by mrPsycho** [comment]
@volkodavs exuse me, but what did you do?

**Comment by volkodavs** [comment]
What i did to solve problem?

**Comment by mrPsycho** [comment]
@volkodavs yes :)

what does it mean ".html_safe solve problem"?

**Comment by volkodavs** [comment]
At file init.rb add html_safe for all macro, but i'm not recomend you do this as i mentioned before.  
Example: 
...
      out = GoogleSpreadsheetMacros.googless_macro(obj, args).html_safe
....

**Comment by mrPsycho** [comment]
thanks, 
im using it only for private installation. 

now i see that only spreadsheets working, but docs - not. only plain  iframe is showing...
but, i'm using 2.5.2
